### PR TITLE
Move to new api endpoints

### PR DESCRIPTION
**Pull request by hanzketup**
Swish AB has changed technical partners for their api and as an effect endpoints and client certificates has changed as well. This change is effective as of 30/6 - 2018.
Offical statement from swish: https://developer.getswish.se/content/uploads/2018/05/Swish_Press_API_29Juni_180516.pdf

### CODE REVIEW

**Comment by MadSpindel** [comment]
The build is failing:
`AssertionError: None != 'https://example.com/api/swishcb/refunds'`

Have Swish changed the response object?

**Comment by hanzketup** [comment]
Seems to be on swish side. 
callbackUrl is present in the response object but set to None, even though callbackUrl is present in the Posted data.
Contacted the new swish technical support, I'll keep you posted on any response.

**Comment by hanzketup** [comment]
Swish technical support just confirmed that its their fault and their devs are working on it.

**Comment by hanzketup** [comment]
All green on the tests, looks like they finally got around to fixing the problem.

**Pull request merged**
